#!/bin/bash
# SCRIPT DE LANCEMENT RAPIDE - TOUS LES SCRAPERS

echo "🚀 SCRAPERS AMAZON DISPONIBLES"
echo "================================"

echo "  1. Roman                                   "
echo "  2. Poésie                                  "
echo "  3. Théâtre                                 "
echo "  4. Essai                                   "
echo "  5. Nouvelle                                "
echo "  6. Autobiographie                          "
echo "  7. Biographie                              "
echo "  8. Mémoires                                "
echo "  9. Journal                                 "
echo " 10. Correspondance                          "
echo " 11. Science-Fiction                         "
echo " 12. Fantasy                                 "
echo " 13. Fantastique                             "
echo " 14. Thriller                                "
echo " 15. Policier                                "
echo " 16. Mystère                                 "
echo " 17. Suspense                                "
echo " 18. Horreur                                 "
echo " 19. Romance                                 "
echo " 20. Historique                              "
echo " 21. Philosophie                             "
echo " 22. Psychologie                             "
echo " 23. Sociologie                              "
echo " 24. Anthropologie                           "
echo " 25. Histoire                                "
echo " 26. Géographie                              "
echo " 27. Politique                               "
echo " 28. Économie                                "
echo " 29. Droit                                   "
echo " 30. Sciences                                "
echo " 31. Mathématiques                           "
echo " 32. Physique                                "
echo " 33. Chimie                                  "
echo " 34. Biologie                                "
echo " 35. Médecine                                "
echo " 36. Informatique                            "
echo " 37. Technologie                             "
echo " 38. Ingénierie                              "
echo " 39. Art                                     "
echo " 40. Sculpture                               "
echo " 41. Photographie                            "
echo " 42. Cinéma                                  "
echo " 43. Musique                                 "
echo " 44. Danse                                   "
echo " 45. Architecture                            "
echo " 46. Design                                  "
echo " 47. Mode                                    "
echo " 48. Cuisine                                 "
echo " 49. Jardinage                               "
echo " 50. Bricolage                               "
echo " 51. Sport                                   "
echo " 52. Santé                                   "
echo " 53. Bien-Être                               "
echo " 54. Développement Personnel                 "
echo " 55. Spiritualité                            "
echo " 56. Religion                                "
echo " 57. Voyage                                  "
echo " 58. Guide                                   "
echo " 59. Tourisme                                "
echo " 60. Enfants                                 "
echo " 61. Jeunesse                                "
echo " 62. Ados                                    "
echo " 63. Adulte                                  "
echo " 64. Seniors                                 "
echo " 65. Scolaire                                "
echo " 66. Universitaire                           "
echo " 67. Professionnel                           "
echo " 68. Bande Dessinée                          "
echo " 69. Bd                                      "
echo " 70. Manga                                   "
echo " 71. Comic                                   "
echo " 72. Album                                   "
echo " 73. Dictionnaire                            "
echo " 74. Encyclopédie                            "
echo " 75. Manuel                                  "
echo " 76. Cours                                   "
echo " 77. Livres de cuisine, cuisine et vins      "
echo " 78. Ésotérisme et Paranormal                "
echo " 79. Mystère et suspense                     "
echo " 80. Bandes dessinées                        "
echo " 81. Thriller et Suspense                    "
echo " 82. Livres pour enfants                     "
echo " 83. Scolaire et Parascolaire                "
echo " 84. Science-fiction et Fantasy              "
echo " 85. Sciences humaines                       "
echo " 86. Littérature française                   "
echo " 87. Littérature étrangère                   "
echo " 88. Polar et Thriller                       "
echo " 89. Romans historiques                      "
echo " 90. Dictionnaires                           "
echo " 91. Encyclopédies                           "
echo " 92. Guides pratiques                        "
echo " 93. Manuels                                 "
echo " 94. BD adultes                              "
echo " 95. BD jeunesse                             "
echo " 96. Mangas Shonen                           "
echo " 97. Mangas Shojo                            "
echo " 98. Light novels                            "
echo " 99. Géologie                                "
echo "100. Peinture                                "
echo "101. Électronique                            "
echo "102. Mécanique                               "
echo "103. Construction                            "

echo "================================"
echo "Pour lancer un scraper:"
echo "  python3 scraper_[nom].py"
echo ""
echo "Exemple: python3 scraper_ados.py"
echo "         python3 scraper_manga.py"
echo ""
echo "RECOMMANDATION: Lancer 3-4 terminaux max simultanément"
